name: "Deploy"

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENCE
      - .gitignore

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          github-server-url: 'https://githubfast.com'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmmirror.com
      - run: npm install -g yarn

      - name: yarn install 
        run: yarn install

      - name: yarn build
        run: yarn generate

      - name: clean old files
        run: rm -rf /opt/1panel/apps/openresty/openresty/www/sites/zblog/index/*

      - name: move new files to website directory
        run: mv ./.output/public/* /opt/1panel/apps/openresty/openresty/www/sites/zblog/index

      - name: change owner
        run: chown -R zayn:zayn /opt/1panel/apps/openresty/openresty/www/sites/zblog/index

      

