name: "Deploy"

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENCE
      - .gitignore

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          github-server-url: 'https://kkgithub.com'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmmirror.com
      - run: npm install -g yarn

      - name: yarn install 
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: clean old files
        run: rm -rf /home/zayn/website/*

      - name: move new files to website directory
        run: mv ./.output/* /home/zayn/website/

      - name: change owner
        run: chown -R zayn:zayn /home/zayn/website

      - name: restart docker pod
        run: sudo docker restart z_blog
      

