name: "Deploy"

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENCE
      - .gitignore

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: manual check output
        run: | 
          cd /tmp/blog
          git fetch --all
          git reset --hard origin/main
          git pull
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmmirror.com
      - run: npm install -g yarn

      - name: yarn install 
        run: yarn install

      - name: yarn build
        run: yarn generate

      - name: clean old files
        run: rm -rf /home/zayn/website/*

      - name: move new files to website directory
        run: mv ./.output/public/* /home/zayn/website/*

      - name: restart docker pod
        run: sudo docker restart z_blog
      

